'use client';

import { useMemo, useState } from 'react';
import { ArrowRight, BookOpen, CalendarDays, ChevronRight, Instagram, Mail, Menu, Search, ShieldCheck, Sparkles, X } from 'lucide-react';
import { CGJLogo } from '@/components/CGJLogo';

type Taxonomy = { id: string; name: string; slug: string };
type Post = {
  id: string;
  title: string;
  slug: string;
  excerpt: string | null;
  content: string;
  cover_image_url: string | null;
  cover_image_alt: string | null;
  featured: boolean;
  published_at: string | null;
  updated_at: string;
  category: Taxonomy | null;
  tags: Taxonomy[];
};

const heroImage = 'https://images.pexels.com/photos/8199159/pexels-photo-8199159.jpeg?auto=compress&cs=tinysrgb&h=650&w=940';

function Logo() {
  return <a href="/" className="flex items-center gap-3 focus-ring" aria-label="CGJ home"><CGJLogo /><span><strong className="block text-[15px] tracking-[.13em] text-[#10223c]">CGJ</strong><span className="block text-[10px] font-bold uppercase tracking-[.1em] text-[#5b6b78]">NUSRL · RANCHI</span></span></a>;
}

function Header({ onSearch }: { onSearch: () => void }) {
  const [open, setOpen] = useState(false);
  return <header className="sticky top-0 z-30 border-b border-[#dfe4e5]/80 bg-[#f8f6f0]/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><Logo /><nav className="hidden items-center gap-8 text-sm font-semibold text-[#526172] md:flex"><a className="hover:text-[#ef765d]" href="#journal">Journal</a><a className="hover:text-[#ef765d]" href="#about">About CGJ</a><a className="hover:text-[#ef765d]" href="#events">Events</a><a className="hover:text-[#ef765d]" href="#publications">Publications</a></nav><div className="flex items-center gap-3"><button onClick={onSearch} className="focus-ring grid h-10 w-10 place-items-center rounded-full border border-[#cbd5d7] text-[#10223c] hover:border-[#ef765d] hover:text-[#ef765d]" aria-label="Search the journal"><Search size={17} /></button><a href="/admin" className="hidden rounded-full bg-[#10223c] px-5 py-2.5 text-sm font-bold text-white transition hover:bg-[#ef765d] md:block">Admin login</a><button onClick={() => setOpen(!open)} className="focus-ring grid h-10 w-10 place-items-center rounded-full border border-[#cbd5d7] md:hidden" aria-label="Menu">{open ? <X size={18} /> : <Menu size={18} />}</button></div></div>{open && <nav className="border-t border-[#dfe4e5] px-5 py-4 md:hidden"><div className="flex flex-col gap-4 text-sm font-semibold"><a href="#journal" onClick={() => setOpen(false)}>Journal</a><a href="#about" onClick={() => setOpen(false)}>About CGJ</a><a href="#events" onClick={() => setOpen(false)}>Events</a><a href="#publications" onClick={() => setOpen(false)}>Publications</a><a href="/admin">Admin login</a></div></nav>}</header>;
}

function Tag({ children }: { children: React.ReactNode }) {
  return <span className="rounded-full bg-[#e4f4f3] px-3 py-1 text-[11px] font-bold uppercase tracking-[.08em] text-[#18727a]">{children}</span>;
}

function postDate(post: Post) {
  return new Date(post.published_at ?? post.updated_at).toLocaleDateString('en-IN', { year: 'numeric', month: 'short', day: 'numeric' });
}

function PostCard({ post, large = false }: { post: Post; large?: boolean }) {
  const category = post.category?.name ?? 'Journal';
  return <a href={`/post/${post.slug}`} className={`group block ${large ? 'md:col-span-2' : ''}`}><div className={`relative overflow-hidden rounded-[2px] bg-[#dbe8e7] ${large ? 'aspect-[1.7]' : 'aspect-[1.25]'}`}>{post.cover_image_url ? <img src={post.cover_image_url} alt={post.cover_image_alt || post.title} className="h-full w-full object-cover transition duration-700 group-hover:scale-105" /> : <div className="grid h-full place-items-center bg-[#e4f4f3] px-6 text-center font-display text-2xl text-[#18727a]">CGJ Journal</div>}<div className="absolute inset-0 bg-gradient-to-t from-[#10223c]/80 via-transparent to-transparent" /><span className="absolute left-4 top-4 rounded-full bg-[#f8f6f0] px-3 py-1 text-[10px] font-bold uppercase tracking-[.1em] text-[#10223c]">{category}</span>{large && <div className="absolute bottom-5 left-5 right-5 text-white"><p className="mb-2 text-xs font-semibold uppercase tracking-[.15em] text-[#a9e2df]">{postDate(post)}</p><h3 className="max-w-2xl font-display text-3xl leading-tight md:text-5xl">{post.title}</h3></div>}</div>{!large && <div className="pt-4"><p className="mb-2 text-[11px] font-bold uppercase tracking-[.12em] text-[#ef765d]">{category} · {postDate(post)}</p><h3 className="font-display text-2xl leading-tight group-hover:text-[#ef765d]">{post.title}</h3>{post.excerpt && <p className="mt-2 text-sm leading-6 text-[#61707b]">{post.excerpt}</p>}</div>}</a>;
}

function Footer() {
  return <footer className="bg-[#10223c] text-white"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-14 md:grid-cols-[1.5fr_1fr_1fr] lg:px-8"><div><div className="mb-4 flex items-center gap-3"><CGJLogo size="sm" /><span className="font-display text-2xl">Centre for Gender Justice</span></div><p className="max-w-md text-sm leading-7 text-[#b9c5cd]">A student and faculty-facing space for research, learning, dialogue, and action at NUSRL, Ranchi.</p></div><div><p className="eyebrow mb-4 text-[#a9e2df]">Explore</p><div className="flex flex-col gap-3 text-sm text-[#d2dce0]"><a href="#journal">The journal</a><a href="#events">Events & activities</a><a href="#publications">Publications</a><a href="#about">About the Centre</a></div></div><div><p className="eyebrow mb-4 text-[#a9e2df]">Connect</p><div className="flex flex-col gap-3 text-sm text-[#d2dce0]"><a className="flex items-center gap-2" href="mailto:cgj@nusrlranchi.ac.in"><Mail size={15} /> cgj@nusrlranchi.ac.in</a><a className="flex items-center gap-2" href="https://www.instagram.com/cgj_nusrl/"><Instagram size={15} /> @cgj_nusrl</a><p className="mt-4 text-xs text-[#8fa0ac]">National University of Study and Research in Law, Ranchi</p></div></div></div><div className="border-t border-white/10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-2 px-5 py-5 text-xs text-[#8fa0ac] md:flex-row lg:px-8"><span>© {new Date().getFullYear()} Centre for Gender Justice</span><span>Content platform for CGJ · NUSRL Ranchi</span></div></div></footer>;
}

function SearchPanel({ posts, close }: { posts: Post[]; close: () => void }) {
  const [query, setQuery] = useState('');
  const found = useMemo(() => posts.filter((post) => `${post.title} ${post.excerpt ?? ''} ${post.content} ${post.category?.name ?? ''} ${post.tags.map((tag) => tag.name).join(' ')}`.toLowerCase().includes(query.toLowerCase())).slice(0, 8), [posts, query]);
  return <div className="fixed inset-0 z-50 bg-[#10223c]/70 p-5 backdrop-blur-sm"><div className="mx-auto mt-20 max-w-2xl rounded-[2px] bg-[#fffdf8] p-6 shadow-2xl md:p-8"><div className="mb-6 flex items-center justify-between"><div><p className="eyebrow text-[#ef765d]">Search the journal</p><h2 className="mt-2 font-display text-3xl">Find a conversation</h2></div><button onClick={close} aria-label="Close search"><X /></button></div><div className="flex items-center gap-3 border-b-2 border-[#10223c] pb-3"><Search size={20} /><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Try a topic, category, or phrase" className="w-full bg-transparent text-base outline-none" /></div><div className="mt-6 space-y-4">{query && found.map((post) => <a key={post.id} href={`/post/${post.slug}`} onClick={close} className="block border-b border-[#dfe4e5] pb-3"><p className="text-xs font-bold uppercase tracking-[.1em] text-[#ef765d]">{post.category?.name ?? 'Journal'}</p><p className="mt-1 font-display text-xl">{post.title}</p></a>)}{query && !found.length && <p className="text-sm text-[#61707b]">No published articles match that search.</p>}{!query && <p className="text-sm leading-7 text-[#61707b]">Search across published essays, field notes, and journal tags.</p>}</div></div></div>;
}

export function HomeClient({ initialPosts, initialCategories, initialTags, initialError, initialCategory, initialTag }: { initialPosts: Post[]; initialCategories: Taxonomy[]; initialTags: Taxonomy[]; initialError?: string; initialCategory: string | null; initialTag: string | null }) {
  const [searchOpen, setSearchOpen] = useState(false);
  const [category, setCategory] = useState<string | null>(initialCategory);
  const [tag, setTag] = useState<string | null>(initialTag);
  const filteredPosts = useMemo(() => initialPosts.filter((post) => (!category || post.category?.slug === category) && (!tag || post.tags.some((item) => item.slug === tag))), [initialPosts, category, tag]);
  const featured = filteredPosts.find((post) => post.featured) ?? filteredPosts[0];
  const remaining = featured ? filteredPosts.filter((post) => post.id !== featured.id) : [];

  return <><Header onSearch={() => setSearchOpen(true)} /><main><section className="paper-grid relative overflow-hidden"><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 pb-20 pt-16 md:grid-cols-[1.05fr_.95fr] md:pb-28 md:pt-24 lg:px-8"><div className="relative z-10"><p className="eyebrow text-[#ef765d]">A space for gender justice</p><h1 className="mt-5 max-w-3xl font-display text-5xl leading-[1.05] text-[#10223c] md:text-7xl">Ideas that make <span className="italic text-[#ef765d]">room</span> for everyone.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#5b6b78]">The editorial home of the Centre for Gender Justice at NUSRL, Ranchi — for careful research, shared learning, and conversations that move us towards a more equitable world.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#journal" className="group flex items-center gap-3 rounded-full bg-[#10223c] px-6 py-3.5 text-sm font-bold text-white transition hover:bg-[#ef765d]">Read the journal <ArrowRight size={17} className="transition group-hover:translate-x-1" /></a><a href="#about" className="rounded-full border border-[#aab8bc] px-6 py-3.5 text-sm font-bold text-[#10223c] hover:border-[#ef765d] hover:text-[#ef765d]">About CGJ</a></div></div><div className="relative mx-auto w-full max-w-[510px]"><div className="absolute -right-4 -top-5 h-32 w-32 rounded-full bg-[#f7c96d]/70 blur-[1px]" /><div className="absolute -bottom-7 -left-5 h-36 w-36 rounded-full bg-[#a9e2df]/80" /><div className="drift relative overflow-hidden rounded-[50%_50%_4px_4px] border-[12px] border-[#10223c] bg-[#ef765d] shadow-2xl"><img src={heroImage} alt="Students in a classroom discussion" className="aspect-[.9] w-full object-cover mix-blend-multiply opacity-90" /><div className="absolute inset-0 bg-[#10223c]/20" /><div className="absolute bottom-7 left-7 right-7 border-t border-white/40 pt-3 text-white"><p className="text-xs font-bold uppercase tracking-[.18em]">Research · Dialogue · Action</p></div></div><div className="absolute -bottom-6 -right-4 rounded-full bg-[#f8f6f0] px-5 py-4 text-center shadow-lg"><p className="font-display text-2xl text-[#10223c]">CGJ</p><p className="text-[9px] font-bold uppercase tracking-[.1em] text-[#ef765d]">NUSRL Ranchi</p></div></div></div></section>
    <section id="journal" className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="mb-8 flex items-end justify-between gap-4"><div><p className="eyebrow text-[#ef765d]">From the journal</p><h2 className="mt-3 font-display text-4xl md:text-5xl">Recent thinking</h2></div><button onClick={() => setSearchOpen(true)} className="hidden items-center gap-2 text-sm font-bold text-[#10223c] hover:text-[#ef765d] sm:flex">Search articles <ChevronRight size={17} /></button></div>{(initialCategories.length > 0 || initialTags.length > 0) && <div className="mb-9 space-y-3"><div className="flex flex-wrap gap-2"><button onClick={() => { setCategory(null); setTag(null); }} className={`rounded-full border px-3 py-1.5 text-xs font-bold ${!category && !tag ? 'border-[#10223c] bg-[#10223c] text-white' : 'border-[#cbd5d7] text-[#526172]'}`}>All writing</button>{initialCategories.map((item) => <button key={item.id} onClick={() => { setCategory(category === item.slug ? null : item.slug); setTag(null); }} className={`rounded-full border px-3 py-1.5 text-xs font-bold ${category === item.slug ? 'border-[#18727a] bg-[#e4f4f3] text-[#18727a]' : 'border-[#cbd5d7] text-[#526172]'}`}>{item.name}</button>)}</div>{initialTags.length > 0 && <div className="flex flex-wrap gap-2">{initialTags.map((item) => <button key={item.id} onClick={() => { setTag(tag === item.slug ? null : item.slug); setCategory(null); }} className={`text-xs ${tag === item.slug ? 'font-bold text-[#ef765d]' : 'text-[#61707b] hover:text-[#ef765d]'}`}>#{item.name}</button>)}</div>}</div>}{initialError ? <div className="border border-[#ef765d] bg-[#fff4f0] p-5 text-sm text-[#b94e3a]">{initialError}</div> : !featured ? <div className="border border-dashed border-[#cbd5d7] p-10 text-center"><h3 className="font-display text-3xl text-[#10223c]">{category || tag ? 'No matching articles yet.' : 'The journal is getting ready.'}</h3><p className="mt-3 text-sm text-[#61707b]">{category || tag ? 'Try another category or tag.' : 'Published articles will appear here.'}</p></div> : <div className="grid gap-10 md:grid-cols-4"><PostCard post={featured} large />{remaining.map((post) => <div key={post.id} className="md:col-span-2"><PostCard post={post} /></div>)}</div>}</section>
    <section id="about" className="bg-[#e4f4f3]"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-20 md:grid-cols-[.8fr_1.2fr] md:py-28 lg:px-8"><div><p className="eyebrow text-[#18727a]">About the Centre</p><h2 className="mt-4 max-w-md font-display text-4xl leading-tight text-[#10223c] md:text-5xl">Learning with, not just about, justice.</h2></div><div className="max-w-2xl"><p className="text-xl leading-8 text-[#334c58]">The Centre for Gender Justice is an integral centre of learning at NUSRL, aimed at fostering an inclusive and equitable society through research, legal awareness, and action-oriented engagement.</p><p className="mt-5 leading-7 text-[#526c73]">This platform is a growing archive of the Centre’s work and a place for students, researchers, practitioners, and communities to share knowledge.</p><a href="mailto:cgj@nusrlranchi.ac.in" className="mt-7 inline-flex items-center gap-2 font-bold text-[#18727a] hover:text-[#ef765d]">Start a conversation <ArrowRight size={17} /></a></div></div></section>
    <section id="events" className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="grid gap-10 md:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow text-[#ef765d]">Events & activities</p><h2 className="mt-4 font-display text-4xl leading-tight md:text-5xl">Where ideas meet the world.</h2><p className="mt-5 max-w-sm leading-7 text-[#61707b]">From campus conversations to legal awareness initiatives, explore the work behind the writing.</p></div><div className="grid gap-4"><div className="flex gap-5 border-y border-[#d3dcdd] py-5"><div className="grid h-14 w-14 shrink-0 place-items-center rounded-full bg-[#f7c96d] text-center"><CalendarDays size={20} /></div><div><p className="eyebrow text-[#ef765d]">Activity report · Coming soon</p><h3 className="mt-2 font-display text-2xl">Community conversations on gender rights</h3><p className="mt-2 text-sm leading-6 text-[#61707b]">Verified event records will be added to the growing archive.</p></div></div><div className="flex gap-5 border-b border-[#d3dcdd] py-5"><div className="grid h-14 w-14 shrink-0 place-items-center rounded-full bg-[#a9e2df]"><ShieldCheck size={20} /></div><div><p className="eyebrow text-[#18727a]">Learning series · Coming soon</p><h3 className="mt-2 font-display text-2xl">Gender-sensitive institutions</h3><p className="mt-2 text-sm leading-6 text-[#61707b]">Programmes and reports will be published here as they are verified.</p></div></div></div></div></section>
    <section id="publications" className="border-t border-[#dfe4e5] bg-[#fffdf8]"><div className="mx-auto grid max-w-7xl items-center gap-10 px-5 py-20 md:grid-cols-[1.15fr_.85fr] md:py-24 lg:px-8"><div><p className="eyebrow text-[#ef765d]">Publications</p><h2 className="mt-4 max-w-2xl font-display text-4xl leading-tight md:text-5xl">A growing library for deeper reading.</h2><p className="mt-5 max-w-xl leading-7 text-[#61707b]">Make reports, newsletters, seminar papers, and other institutional publications easy to discover and download.</p><a href="/publications" className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#10223c] px-5 py-3 text-sm font-bold text-white hover:bg-[#ef765d]">Browse publications <BookOpen size={16} /></a></div><div className="relative mx-auto w-full max-w-sm rotate-2 bg-[#10223c] p-3 shadow-xl"><div className="flex aspect-[.8] flex-col justify-between bg-[#ef765d] p-6 text-[#10223c]"><Sparkles size={27} /><div><p className="eyebrow">CGJ / NUSRL</p><p className="mt-2 font-display text-4xl leading-none">Knowledge<br /><i>in common.</i></p></div><p className="text-xs font-bold uppercase tracking-[.1em]">Publication library</p></div></div></div></section></main><Footer />{searchOpen && <SearchPanel posts={initialPosts} close={() => setSearchOpen(false)} />}</>;
}
